export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const COURSES_FETCHED = 'COURSES_FETCHED';
export const COURSE_FETCHED = 'COURSE_FETCHED';
export const COURSE_SELECTED = 'COURSE_SELECTED';

export const LECTURES_FETCHED = 'LECTURES_FETCHED';
export const LECTURE_FETCHED = 'LECTURE_FETCHED';
export const LECTURE_SELECTED = 'LECTURE_SELECTED';

export const GET_ERRORS = 'GET_ERRORS';
