export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_INSTRUCTOR = 'SET_INSTRUCTOR';

export const COURSES_FETCHED = 'COURSES_FETCHED';
export const COURSE_FETCHED = 'COURSE_FETCHED';
export const COURSES_SUGGESTED = 'COURSES_SUGGESTED';
export const COURSE_SELECTED = 'COURSE_SELECTED';

export const LECTURES_FETCHED = 'LECTURES_FETCHED';
export const LECTURE_FETCHED = 'LECTURE_FETCHED';
export const LECTURE_SELECTED = 'LECTURE_SELECTED';

export const QUESTIONS_FETCHED = 'QUESTIONS_FETCHED';
export const QUESTION_SELECTED = 'QUESTION_SELECTED';

export const ANSWERS_FETCHED = 'ANSWERS_FETCHED';

export const DELETE_TRIGGERED = 'DELETE_TRIGGERED';
export const DELETE_APPROVED = 'DELETE_APPROVED';
export const DELETE_RESET = 'DELETE_RESET';

export const GET_ERRORS = 'GET_ERRORS';
